#!/usr/bin/env bash
#
# Builds Nuvi.app from the SwiftPM executable: compiles, assembles the bundle,
# and ad-hoc signs it with the entitlements. Usage: ./scripts/build-app.sh [debug|release]
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${1:-release}"

echo "==> Building Nuvi ($CONFIG)"
swift build -c "$CONFIG" --package-path "$ROOT"

BIN_PATH="$(swift build -c "$CONFIG" --package-path "$ROOT" --show-bin-path)"
APP="$ROOT/build/Nuvi.app"

echo "==> Assembling bundle at $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN_PATH/Nuvi" "$APP/Contents/MacOS/Nuvi"
cp "$ROOT/Resources/Info.plist" "$APP/Contents/Info.plist"

# App icon (generated by scripts/make-icon.sh). Optional — skip if missing.
if [ -f "$ROOT/Resources/Nuvi.icns" ]; then
    cp "$ROOT/Resources/Nuvi.icns" "$APP/Contents/Resources/Nuvi.icns"
fi

# Copy any SwiftPM resource bundles produced alongside the binary.
for bundle in "$BIN_PATH"/*.bundle; do
    [ -e "$bundle" ] && cp -R "$bundle" "$APP/Contents/Resources/"
done

# Also copy the models catalog loose into Resources. SPM's Bundle.module accessor
# does not look in Contents/Resources, so the app resolves the catalog via
# Bundle.main instead; this guarantees it's found in the packaged .app.
CATALOG="$ROOT/Sources/Nuvi/Infrastructure/Settings/ModelsCatalog.json"
[ -f "$CATALOG" ] && cp "$CATALOG" "$APP/Contents/Resources/ModelsCatalog.json"

# Sign with a STABLE identity so macOS keeps the Microphone / Speech Recognition /
# Accessibility TCC grants across rebuilds. This is not cosmetic: an ad-hoc signature
# changes the code identity on every rebuild, which invalidates the Speech Recognition
# grant and makes SpeechAnalyzer return zero results — the app opens the mic but never
# transcribes. Prefer an explicit identity, else auto-pick the first Apple Development
# certificate available, and only fall back to ad-hoc as a last resort (with a warning).
#   export NUVI_SIGN_IDENTITY="Apple Development: you@example.com (TEAMID)"
SIGN_ID="${NUVI_SIGN_IDENTITY:-}"
if [ -z "$SIGN_ID" ]; then
    SIGN_ID="$(security find-identity -v -p codesigning 2>/dev/null \
        | rg -o '"(Apple Development|Developer ID Application): [^"]+"' \
        | head -1 | sed 's/^"//; s/"$//')"
fi

if [ -z "$SIGN_ID" ]; then
    echo "==> WARNING: no stable signing identity found — falling back to ad-hoc."
    echo "    TCC grants (Microphone/Speech/Accessibility) will be LOST on each rebuild,"
    echo "    which breaks transcription. Set NUVI_SIGN_IDENTITY to a real certificate."
    SIGN_ID="-"
else
    echo "==> Signing with identity: $SIGN_ID"
fi

# --options runtime enables the Hardened Runtime (library-validation, no unsigned
# code injection) — required for notarization and a real hardening baseline.
codesign --force --options runtime --deep --sign "$SIGN_ID" \
    --entitlements "$ROOT/Resources/Nuvi.entitlements" \
    "$APP" 2>/dev/null || codesign --force --options runtime --deep --sign "$SIGN_ID" "$APP"

# Install into /Applications so `open -a Nuvi` / Spotlight always launch THIS build.
# Skipping this is how a stale /Applications/Nuvi.app silently shadows new builds.
# Same signing identity keeps the TCC grants across reinstalls.
INSTALLED="/Applications/Nuvi.app"
echo "==> Installing to $INSTALLED"
rm -rf "$INSTALLED"
cp -R "$APP" "$INSTALLED"

echo "==> Done."
echo "    Installed: $INSTALLED"
echo "    Launch:    open \"$INSTALLED\"   (or just: open -a Nuvi)"
echo
echo "    Do NOT run the inner binary directly (\"$APP/Contents/MacOS/Nuvi\"):"
echo "    launched that way the process is not bound to the app bundle, so TCC"
echo "    can't see NSSpeechRecognitionUsageDescription and the app SIGABRTs on the"
echo "    first speech access. Always launch with 'open'."
echo
echo "    To read runtime logs, launch with 'open' and in another terminal run:"
echo "        log stream --predicate 'process == \"Nuvi\"' --info --debug"
echo
echo "First run: grant Microphone + Speech Recognition + Accessibility in"
echo "System Settings > Privacy & Security."
